# Site settings
title: The Prescher Lab
email: 
description: > # this means to ignore newlines until "baseurl:"
  Crafting novel probes to spy on cells.
baseurl: "/~jpresche" # the subpath of your site, e.g. /blog
url: "http://www.chem.uci.edu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
#permalink: pretty

# Collection Names
collections:
    research_intros:
        output: true
    resources:
        output: true